import { aliases, mdi } from 'vuetify/iconsets/mdi-svg'
import { 
  mdiAccount, 
  mdiArchiveOutline,
  mdiArrowLeft,
  mdiArrowRight,
  mdiBackspace,
  mdiButtonCursor,
  mdiCalendarEdit,
  mdiCameraFlip,
  mdiCancel,
  mdiCardPlusOutline,
  mdiCheck,
  mdiCheckboxMarked,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiChevronUp,
  mdiCircle,
  mdiClose,
  mdiCloudCheck,
  mdiCloudRemove,
  mdiCloudSync,
  mdiCloudUpload,
  mdiCog, 
  mdiCommentQuote, 
  mdiContentSave,
  mdiCubeOutline, 
  mdiDebugStepOver, 
  mdiDelete,
  mdiDragVariant,
  mdiEmail,
  mdiEraser,
  mdiEraserVariant,
  mdiFileDelimited,
  mdiFileDelimitedOutline,
  mdiFileOutline,
  mdiFilter,
  mdiFingerprint,
  mdiHelpCircleOutline,
  mdiInformation,
  mdiListBox,
  mdiLogout,
  mdiMagnify,
  mdiMenuDown,
  mdiMenuUp,
  mdiMoveResizeVariant,
  mdiNumeric,
  mdiOpenInNew,
  mdiPalette,
  mdiPartyPopper,
  mdiPencil, 
  mdiPencilOff, 
  mdiPhone, 
  mdiPrinter, 
  mdiRefresh,
  mdiRestart,
  mdiSend,
  mdiTextBox,
  mdiThemeLightDark,
  mdiUndo,
  mdiViewCarousel,
  mdiViewColumn,
  mdiViewList,
  mdiWindowMaximize, 
  mdiYoutube} from '@mdi/js'
import type { IconAliases, IconOptions } from 'vuetify'

export function useIcons(icons?: Partial<IconAliases>): IconOptions {
    return {
        defaultSet: 'mdi',
        aliases: {
            ...aliases,
            account: mdiAccount,
            'archive-outline': mdiArchiveOutline,
            'arrow-left': mdiArrowLeft,
            'arrow-right': mdiArrowRight,
            backspace: mdiBackspace,
            'button-cursor': mdiButtonCursor,
            'calendar-edit': mdiCalendarEdit,
            'camera-flip': mdiCameraFlip,
            cancel: mdiCancel,
            'card-plus-outline': mdiCardPlusOutline,
            check: mdiCheck,
            'chevron-down': mdiChevronDown,
            'chevron-left': mdiChevronLeft,
            'chevron-right': mdiChevronRight,
            'chevron-up': mdiChevronUp,
            'checkbox-marked': mdiCheckboxMarked,
            circle: mdiCircle,
            close: mdiClose,
            'cloud-check': mdiCloudCheck,
            'cloud-remove': mdiCloudRemove,
            'cloud-sync': mdiCloudSync,
            'cloud-upload': mdiCloudUpload,
            cog: mdiCog,
            'content-save': mdiContentSave,
            'cube-outline': mdiCubeOutline,
            'debug-step-over': mdiDebugStepOver,
            delete: mdiDelete,
            'drag-variant': mdiDragVariant,
            email: mdiEmail,
            eraser: mdiEraser,
            'eraser-variant': mdiEraserVariant,
            'feedback': mdiCommentQuote,
            'file-delimited': mdiFileDelimited,
            'file-delimited-outline': mdiFileDelimitedOutline,
            'file-outline': mdiFileOutline,
            filter: mdiFilter,
            fingerprint: mdiFingerprint,
            'help-circle-outline': mdiHelpCircleOutline,
            information: mdiInformation,
            'list-box': mdiListBox,
            logout: mdiLogout,
            magnify: mdiMagnify,
            'menu-down': mdiMenuDown,
            'menu-up': mdiMenuUp,
            'move-resize-variant': mdiMoveResizeVariant,
            numeric: mdiNumeric,
            'open-in-new': mdiOpenInNew,
            palette: mdiPalette,
            'party': mdiPartyPopper,
            pencil: mdiPencil,
            'pencil-off': mdiPencilOff,
            phone: mdiPhone,
            printer: mdiPrinter,
            refresh: mdiRefresh,
            restart: mdiRestart,
            send: mdiSend,
            'theme-light-dark': mdiThemeLightDark,
            'text-box': mdiTextBox,
            undo: mdiUndo,
            'view-carousel': mdiViewCarousel,
            'view-column': mdiViewColumn,
            'view-list': mdiViewList,
            'window-maximize': mdiWindowMaximize,
            youtube: mdiYoutube,
            ...(icons ?? {})
        },
        sets: {
            mdi
        }
    }
}