import { aliases, mdi } from 'vuetify/iconsets/mdi-svg'
import { 
  mdiAccount, 
  mdiArchiveOutline,
  mdiArrowLeft,
  mdiArrowRight,
  mdiBackspace,
  mdiCalendarEdit,
  mdiCameraFlip,
  mdiCancel,
  mdiCheck,
  mdiChevronDown,
  mdiChevronUp,
  mdiCircle,
  mdiClose,
  mdiCog, 
  mdiContentSave,
  mdiCubeOutline, 
  mdiDelete,
  mdiDragVariant,
  mdiEraser,
  mdiEraserVariant,
  mdiFileDelimited,
  mdiFileDelimitedOutline,
  mdiFilter,
  mdiFingerprint,
  mdiHelpCircleOutline,
  mdiLogout,
  mdiMagnify,
  mdiMenuDown,
  mdiMoveResizeVariant,
  mdiPencil, 
  mdiPencilOff, 
  mdiRefresh,
  mdiThemeLightDark,
  mdiUndo,
  mdiViewColumn,
  mdiWindowMaximize, 
  mdiYoutube} from '@mdi/js'
import type { IconAliases, IconOptions } from 'vuetify'

export function useIcons(icons?: Partial<IconAliases>): IconOptions {
    return {
        defaultSet: 'mdi',
        aliases: {
            ...aliases,
            account: mdiAccount,
            'archive-outline': mdiArchiveOutline,
            'arrow-left': mdiArrowLeft,
            'arrow-right': mdiArrowRight,
            backspace: mdiBackspace,
            'calendar-edit': mdiCalendarEdit,
            'camera-flip': mdiCameraFlip,
            cancel: mdiCancel,
            check: mdiCheck,
            'chevron-up': mdiChevronUp,
            'chevron-down': mdiChevronDown,
            circle: mdiCircle,
            close: mdiClose,
            cog: mdiCog,
            'content-save': mdiContentSave,
            'cube-outline': mdiCubeOutline,
            delete: mdiDelete,
            'drag-variant': mdiDragVariant,
            eraser: mdiEraser,
            'eraser-variant': mdiEraserVariant,
            'file-delimited': mdiFileDelimited,
            'file-delimited-outline': mdiFileDelimitedOutline,
            filter: mdiFilter,
            fingerprint: mdiFingerprint,
            'help-circle-outline': mdiHelpCircleOutline,
            logout: mdiLogout,
            magnify: mdiMagnify,
            'menu-down': mdiMenuDown,
            'move-resize-variant': mdiMoveResizeVariant,
            pencil: mdiPencil,
            'pencil-off': mdiPencilOff,
            refresh: mdiRefresh,
            'theme-light-dark': mdiThemeLightDark,
            undo: mdiUndo,
            'view-column': mdiViewColumn,
            'window-maximize': mdiWindowMaximize,
            youtube: mdiYoutube,
            ...(icons ?? {})
        },
        sets: {
            mdi
        }
    }
}